
version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=fasolink_db
      - POSTGRES_USER=fasolink_user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media # Mount the media volume
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=fasolink_db
      - POSTGRES_USER=fasolink_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data: