# Generated by Django 5.2.6 on 2025-09-18 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_jiji_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listingattribute',
            new_name='api_listing_listing_e2c5c0_idx',
            old_name='api_listinga_listing_3f71fc_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='api_review_seller__20fdb5_idx',
            old_name='api_review_seller_inde',
        ),
        migrations.AlterField(
            model_name='listingattribute',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'seller', 'created_at')},
        ),
    ]
