# Generated by Django 5.2.6 on 2025-09-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_message_content_messageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
