# Generated by Django 5.2.6 on 2025-09-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='lang',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
